"""Update models

Revision ID: f95a35ba9659
Revises: 36cd5b957f95
Create Date: 2026-09-19 10:24:43.013800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95a35ba9659'
down_revision: Union[str, Sequence[str], None] = '36cd5b957f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_scripts', sa.Column('complexity_category', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('code', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('total_marks', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('status', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'assessments', ['code'])
    op.add_column('evaluations', sa.Column('evaluation_time_mins', sa.Integer(), nullable=True))
    op.add_column('marks', sa.Column('question_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'marks', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_column('marks', 'question_id')
    op.drop_column('evaluations', 'evaluation_time_mins')
    op.drop_constraint(None, 'assessments', type_='unique')
    op.drop_column('assessments', 'status')
    op.drop_column('assessments', 'total_marks')
    op.drop_column('assessments', 'code')
    op.drop_column('answer_scripts', 'complexity_category')
    # ### end Alembic commands ###
